# Configuration for Move Issues - https://github.com/dessant/move-issues

deleteCommand: true
closeSourceIssue: true
lockSourceIssue: false
mentionAuthors: true
keepContentMentions: true
moveLabels: false

aliases:
  flutter: flutter/flutter
  sdk: dart-lang/sdk